# indico que version de node usar
FROM node:12

# agrego la carpeta dentro del contenedor
ADD . ./crawl-extractors

# me muevo a la carpeta correspondiente
WORKDIR /crawl-extractors

# inicio el servicio
CMD npm start
