# indico que version de node usar
FROM node:12

# agrego la carpeta dentro del contenedor
ADD . ./search-engine

# me muevo a la carpeta correspondiente
WORKDIR /search-engine

# inicio el servicio
CMD npm start
